version: '3'
services:
  postgres:
    image: postgres:13
    container_name: postgres_db
    environment:
      POSTGRES_USER: salman
      POSTGRES_PASSWORD: salman12345
      POSTGRES_DB: blogdb
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432" 

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: salman@admin.com
      PGADMIN_DEFAULT_PASSWORD: salman12345
    ports:
      - "5050:80" # Expose pgAdmin on port 5050
    depends_on:
      - postgres

  blogapp:
    build: ./blogapp
    container_name: blog_app
    ports:
      - "8000:8000"
    environment:
      DB_HOST: postgres_db
      DB_NAME: blogdb
      DB_USER: salman
      DB_PASS: salman12345
    depends_on:
      - postgres
volumes:
  postgres_data:
    driver: local 